### ISSUE TITLE
Elm package is broken

### ISSUE THREAD

**Issue by raen79** [tricycle/elm-imgix#3]
Hey! Firstly thank you for your package, I am an avid user :) I assume you have changed your account name or moved the package recently as I am getting this error:

```
I downloaded the source code for tricycle/elm-imgix 1.4.0 from:
--
02:08:58.849 | https://github.com/tricycle/elm-imgix/zipball/1.4.0/
02:08:58.849 | But it looks like the hash of the archive has changed since publication:
02:08:58.849 | Expected: 7f9015ad6d29a00ba468020d4baa8101ac30a611
02:08:58.849 | Actual: 80e3d28dc3eaa41d8202c1a9b788d22844e371a4
02:08:58.850 | This usually means that the package author moved the version tag, so report it
02:08:58.850 | to them and see if that is the issue. Folks on Elm slack can probably help as
02:08:58.850 | well.
```

I made a fork and a convenience release until then in case anyone needs it:
https://package.elm-lang.org/packages/raen79/elm-imgix/latest/

**Comment by michaelwebb76** [comment]
Thanks for reporting @raen79 - a long overdue organisation rename has us scrambling today to resolve all of our open-source Elm packages, and unfortunately it seems the only way to address the rename is to re-publish the packages as 1.0.0 under the new organisation name :-/ which we've done https://package.elm-lang.org/packages/bellroy/elm-imgix/latest/
